import type { Metadata } from "next";
import "@/css/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-no-repeat bg-cover bg-center bg-[url('/background.png')]">
        {children}
      </body>
    </html>
  );
}
